---
title: "Exploratory Data"
author: "Nick chapman"
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: 
  github_document: default
  html_notebook: default 
---

## Introduction
This notebook contains the code to explore the data created in the CleanCreate Notebook.

## Dependencies
This notebook requires a few packages:

```{r load-packages}
# tidyverse packages
library(tidycensus)
library(tigris)
library(dplyr)
library(readr)
library(here)
library(naniar)
library(janitor)
library(sf)
library(Hmisc)
library(ggplot2)
```

## Load Data

This Notebook requires data that will be called from the data/clean/ folder:

```{r call-data}
county_rankings<- read_csv(here("data", "clean", "County_Rankings_Clean.csv"))
income_data<- read_csv(here("data", "clean", "MO_Income_Clean.csv"))
population_data<- read.csv(here("data", "clean", "MO_population_Clean.csv"))
heart_attack_data<- read.csv(here("data", "clean", "Heart_Attack_Clean.csv"))
MO_counties<- read_sf(here("data", "clean", "moCounties.shp"))
Black_pop<- read.csv(here("data", "clean", "MO_Race_Clean.csv"))
```

```{r load-corrTable-function}
source(here("source", "corrTable.R"))
```


```{r join heart-population-date}
heart_attack_density<- left_join(heart_attack_data, population_data, by = "GEOID")
```

```{r generate-heart-attack-density}
heart_attack_density %>%
  mutate('Heart_Attack_Density' = ((Number_of_Heart_attacks/Population_Estimate) * 10000)) %>%
  select(-"Number_of_Heart_attacks")-> heart_attack_density
```


```{r create-black-pop-percent}
black_percent <- left_join(population_data, Black_pop, by= "GEOID")

black_pop_percent<- black_percent %>%
  mutate('Percent_Black' = (Number_Black/Population_Estimate)) %>%
  select(-"Population_Estimate")
```

```{r join-all-tables}
income_rankings<- left_join(county_rankings, income_data, by = "GEOID")
heart_income_rankings <- left_join(income_rankings, heart_attack_data, by = "GEOID")
heart_income_Black_rankings <- left_join(heart_income_rankings, black_pop_percent,by = "GEOID")
heart_attack_final<- left_join(heart_income_Black_rankings, heart_attack_density, by = "GEOID")
variables_counties <- left_join(MO_counties,heart_attack_final, by= "GEOID")
```


```{r Corr-Table}
correlation_table <- corrTable(heart_attack_final, coef= "pearson", listwise = TRUE, round = 3, pStar = T, `Adult smoking`, `Adult obesity`, `Food environment index`, `Physical inactivity`,`Access to exercise opportunities`, `Median_Income`, `Percent_Black`, `Heart_Attack_Density`)
```

```{r}
write_csv(correlation_table, here("results", "Correlation.Table", "correlation.table.csv"))
```


```{r GGplot-income-activity}
ggplot(data = heart_attack_final, mapping = aes(x= `Physical inactivity`, y=Median_Income)) +
  geom_point () +
  geom_smooth(method = "lm") -> income_activity_plot

print(income_activity_plot + labs(title="Median Income and Physical Activity of Missouri Counties",
                      y="Median Income (in dollars)", x = "Physically Active Adults (%)"))

ggsave(here("results", "plots", "income_activity_plot.png"), width = 7, height = 4, units = "in", dpi = 500)
```

```{r GGplot-heart_attack_income_lm}
ggplot(data = heart_attack_final, mapping = aes(x= `Heart_Attack_Density`, y = `Median_Income`)) +
  geom_point (position = "jitter")+
  geom_smooth(method = "lm") -> Income_Heart_attack_lm

print(Income_Heart_attack_lm + labs(title="Median Income and Heart Attack Density of Missouri Counties",
                      y="Median Income (in dollars)", x = "Density of Heart Attacks"))

ggsave(here("results", "plots", "Income_Heart_attack_lm.png"), width = 7, height = 4, units = "in", dpi = 500)
```


```{r GGplot-income-activity}
ggplot(data = heart_attack_final, mapping = aes(x= `Food environment index`, y=Median_Income)) +
  geom_point () +
  geom_smooth(method = "lm") -> Food_income_plot

print(Food_income_plot + labs(title="Median Income and Food Environment of Missouri Counties",
                      y="Median Income (in dollars)", x = "Food Environment Index"))

ggsave(here("results", "plots", "Food_income_plot.png"), width = 7, height = 4, units = "in", dpi = 500)
```

```{r GGplot-income-smoking}
ggplot(data = heart_attack_final, mapping = aes(x= `Adult smoking`, y=Median_Income)) +
  geom_point (position = "jitter") +
  geom_smooth(method = "lm") -> smoking_income_plot

print(smoking_income_plot + labs(title="Median Income and Smoking of Missouri Counties",
                      y="Median Income (in dollars)", x = "Adult Smokers (%)"))

ggsave(here("results", "plots", "smoking_income_plot.png"), width = 7, height = 4, units = "in", dpi = 500)
```

```{r GGplot-heart-smoking}
ggplot(data = heart_attack_final, mapping = aes(x= `Heart_Attack_Density`, y=`Adult smoking`)) +
  geom_point (position = "jitter") +
  geom_smooth(method = "lm") -> heart_smoking_plot

print(heart_smoking_plot + labs(title="Smoking and Heart Attacks in Missouri Counties",
                      y="Adult smokers (%)", x = "Density of Heart Attacks"))

ggsave(here("results", "plots", "heart_smoking_plot.png"), width = 7, height = 4, units = "in", dpi = 500)
```




```{r}
ggplot() +
  geom_sf(data = variables_counties, mapping = aes(fill = `Median_Income`))+
  scale_fill_viridis_c(option = "cividis", name = "Median Income",limits = c(10000,40000), direction = -1) +
  labs(
    title = "2017 Missouri \nIncome by County",
    subtitle = "Inflation-adjusted Dollars",
    caption = "Data from the US Census through the ACS"
  ) +
  theme_void() -> GGplot_MO_2017_income
GGplot_MO_2017_income
```
```{r}
ggsave(width = 13.33, height = 6, units = "in",here("results", "maps", "GGplot_MO_income.png"), GGplot_MO_2017_income, dpi = 500)
```


```{r}
ggplot() +
  geom_sf(data = variables_counties, mapping = aes(fill = `Heart_Attack_Density`))+
  scale_fill_viridis_c(option = "cividis", name = "Per Capita \nHeart Attacks", limits= c(1,80), direction = -1) +
  labs(
    title = "2017 Missouri \nHeart Attacks by County",
    subtitle = "Rate per 10,000 individuals",
    caption = "Data from Missouri Department of Health and Human Services"
  ) +
  theme_void() -> GGplot_MO_2017_Heart_Attacks
 GGplot_MO_2017_Heart_Attacks
```

```{r}
ggsave(width = 13.33, height = 6, units = "in",here("results", "maps", "GGplot_MO_Heart_Attacks.png"),  GGplot_MO_2017_Heart_Attacks, dpi = 500)
```